fix gpfs paths

diff --git a/run/FV3HREF_PREP.bsub.in b/run/FV3HREF_PREP.bsub.in
--- a/run/FV3HREF_PREP.bsub.in
+++ b/run/FV3HREF_PREP.bsub.in
@@ -11,8 +11,9 @@
 
 set -eux
 
-trap 'echo "FV3HREF error _MEMBER_ PREP" >> /gpfs/hps/ptmp/$LOGNAME/fv3href/jlogfile_sref' INT TERM ERR
-echo "FV3HREF started _MEMBER_ PREP" >> /gpfs/hps/ptmp/$LOGNAME/fv3href/jlogfile_sref
+MY_PTMP=/gpfs/hps3/ptmp/$LOGNAME
+trap 'echo "FV3HREF error _MEMBER_ PREP" >> $MY_PTMP/fv3href/jlogfile_sref' INT TERM ERR
+echo "FV3HREF started _MEMBER_ PREP" >> $MY_PTMP/fv3href/jlogfile_sref
 
 . /opt/modules/default/init/bash
 module load PrgEnv-intel
@@ -48,4 +49,4 @@ export APRUN="aprun -n 1 -N 1 -j 1 -d 24 -cc depth"
 
 _FV3HREFDIR_/jobs/JFV3HREF_PREP
 
-echo "FV3HREF finished _MEMBER_ PREP" >> /gpfs/hps/ptmp/$LOGNAME/fv3href/jlogfile_sref
+echo "FV3HREF finished _MEMBER_ PREP" >> $MY_PTMP/fv3href/jlogfile_sref
