port jobs and scripts for wrf_prep and wrf_real

diff --git a/run/SREF_PREP.bsub.in b/run/SREF_PREP.bsub.in
--- a/run/SREF_PREP.bsub.in
+++ b/run/SREF_PREP.bsub.in
@@ -3,37 +3,32 @@
 #BSUB -oo _SREFDIR_/run/sref_prep__MODEL___MEMBER_.log
 #BSUB -eo _SREFDIR_/run/sref_prep__MODEL___MEMBER_.log
 #BSUB -J SREF_PREP__MODEL___MEMBER_
-#BSUB -n 16
+#BSUB -n 28
 #BSUB -x
-#BSUB -R span[ptile=8]
+#BSUB -R span[ptile=28]
 #BSUB -W 03:00
-#BSUB -q "devhigh"
+#BSUB -q "dev"
 #BSUB -P SREF-T2O
-#BSUB -a poe
 
-set -aeux
+set -eux
 
-trap 'echo "SREF error _MODEL_ _MEMBER_ PREP" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref' INT TERM ERR
-echo "SREF started _MODEL_ _MEMBER_ PREP" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+trap 'echo "SREF error _MODEL_ _MEMBER_ PREP" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref' INT TERM ERR
+echo "SREF started _MODEL_ _MEMBER_ PREP" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
-. /usrx/local/Modules/3.2.9/init/bash
-module load ibmpe
-module load ics
+. /usrx/local/prod/lmod/lmod/init/bash
+module load lsf/10.1
+module load ips/18.0.1.163
+module load prod_util/1.1.0
+module load grib_util/1.1.0
+module load NetCDF/4.5.0
 
 export OMP_NUM_THREADS=1
-export MP_EUIDEVICE=sn_all
-export MP_EUILIB=us
-export MP_MPILIB=mpich2
-export MP_TASK_AFFINITY=core:1
-
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usrx/local/netcdf-3.6.3/lib
-
 
 export RUN_ENVIR=para
 export envir=prod
 export job=$$
 
-export CONFIG_FILE=_SREFDIR_/parm/sref_para_config_wcoss
+export CONFIG_FILE=_SREFDIR_/parm/sref_para_config_dell
 
 export PDY=_PDY_
 export cyc=_CYC_
@@ -49,8 +44,8 @@ export N_TASK=$LSB_DJOB_NUMPROC
 
 _SREFDIR_/jobs/JSREF_WRF_PREP
 
-echo "SREF finished _MODEL_ _MEMBER_ PREP" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF finished _MODEL_ _MEMBER_ PREP" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
 bsub < _SREFDIR_/run/SREF_REAL__MODEL___MEMBER_.bsub
-echo "SREF waiting _MODEL_ _MEMBER_ REAL" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF waiting _MODEL_ _MEMBER_ REAL" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
