submit calfcsterr job

diff --git a/run/SREF_CALFCSTERR.bsub.in b/run/SREF_CALFCSTERR.bsub.in
--- a/run/SREF_CALFCSTERR.bsub.in
+++ b/run/SREF_CALFCSTERR.bsub.in
@@ -8,17 +8,19 @@
 #BSUB -R span[ptile=1]
 #BSUB -W 01:30
 #BSUB -P SREF-T2O
-#BSUB -q "devhigh"
-#BSUB -a poe
+#BSUB -q "dev"
 
 set -aeux
 
-trap 'echo "SREF error CALFCSTERR" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref' INT TERM ERR
-echo "SREF started CALFCSTERR" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+trap 'echo "SREF error CALFCSTERR" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref' INT TERM ERR
+echo "SREF started CALFCSTERR" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
-. /usrx/local/Modules/3.2.9/init/bash
-module load ibmpe
-module load ics
+. /usrx/local/prod/lmod/lmod/init/bash
+module load lsf/10.1
+module load ips/18.0.1.163
+module load prod_util/1.1.0
+module load grib_util/1.1.0
+module load NetCDF/4.5.0
 
 export OMP_NUM_THREADS=1
 export MP_EUIDEVICE=sn_all
@@ -26,26 +28,23 @@ export MP_EUILIB=us
 export MP_MPILIB=mpich2
 export MP_TASK_AFFINITY=core:1
 
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usrx/local/NetCDF/3.6.3/lib
-
-
 export RUN_ENVIR=para
 export envir=prod
 export job=$$
 
-export CONFIG_FILE=_SREFDIR_/parm/sref_para_config_wcoss
+export CONFIG_FILE=_SREFDIR_/parm/sref_para_config_dell
 
 export PDY=_PDY_
 export cyc=_CYC_
 
 _SREFDIR_/jobs/JSREF_CALFCSTERR
 
-echo "SREF finished CALFCSTERR" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF finished CALFCSTERR" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
 # Submit next job here:
 #bsub < _SREFDIR_/run/SREF_BIAS.bsub
-#echo "SREF waiting BIAS" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+#echo "SREF waiting BIAS" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
 bsub < _SREFDIR_/run/SREF_QPFBIAS.bsub
-echo "SREF waiting QPFBIAS" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF waiting QPFBIAS" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
