port jobs and scripts for wrf fcst step

diff --git a/run/SREF_FCST.bsub.in b/run/SREF_FCST.bsub.in
--- a/run/SREF_FCST.bsub.in
+++ b/run/SREF_FCST.bsub.in
@@ -3,37 +3,33 @@
 #BSUB -oo _SREFDIR_/run/sref_fcst__MODEL___MEMBER_.log
 #BSUB -eo _SREFDIR_/run/sref_fcst__MODEL___MEMBER_.log
 #BSUB -J SREF_FCST__MODEL___MEMBER_
-#BSUB -n 96
+#BSUB -n _TASKS_
 #BSUB -x
-#BSUB -R span[ptile=16]
+#BSUB -R span[ptile=28]
 #BSUB -W 03:00
-#BSUB -q "devhigh"
+#BSUB -q "dev"
 #BSUB -P SREF-T2O
-#BSUB -a poe
 
-set -aeux
+set -eux
 
-trap 'echo "SREF error _MODEL_ _MEMBER_ FCST" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref' INT TERM ERR
-echo "SREF started _MODEL_ _MEMBER_ FCST" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+trap 'echo "SREF error _MODEL_ _MEMBER_ FCST" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref' INT TERM ERR
+echo "SREF started _MODEL_ _MEMBER_ FCST" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
-. /usrx/local/Modules/default/init/bash
+. /usrx/local/prod/lmod/lmod/init/bash
 module purge
-module load lsf
-module load ibmpe
-module load ics
-module load NetCDF
+module load lsf/10.1
+module load ips/18.0.1.163
+module load prod_util/1.1.0
+module load grib_util/1.1.0
+module load NetCDF/4.5.0
 
 export OMP_NUM_THREADS=1
-export MP_EUIDEVICE=sn_all
-export MP_EUILIB=us
-export MP_MPILIB=mpich2
-export MP_TASK_AFFINITY=core:1
 
 export RUN_ENVIR=para
 export envir=prod
 export job=$$
 
-export CONFIG_FILE=_SREFDIR_/parm/sref_para_config_wcoss
+export CONFIG_FILE=_SREFDIR_/parm/sref_para_config_dell
 
 export PDY=_PDY_
 export cyc=_CYC_
@@ -48,14 +44,14 @@ export N_TASK=$LSB_DJOB_NUMPROC
 
 _SREFDIR_/jobs/JSREF_WRF_FCST
 
-echo "SREF finished _MODEL_ _MEMBER_ FCST" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF finished _MODEL_ _MEMBER_ FCST" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
 bsub < _SREFDIR_/run/SREF_POST__MODEL___MEMBER_.bsub
 bsub < _SREFDIR_/run/SREF_POST2__MODEL___MEMBER_.bsub
 bsub < _SREFDIR_/run/SREF_POST3__MODEL___MEMBER_.bsub
 bsub < _SREFDIR_/run/SREF_POST4__MODEL___MEMBER_.bsub
-echo "SREF waiting _MODEL_ _MEMBER_ POST" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
-echo "SREF waiting _MODEL_ _MEMBER_ POST2" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
-echo "SREF waiting _MODEL_ _MEMBER_ POST3" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
-echo "SREF waiting _MODEL_ _MEMBER_ POST4" >> /ptmpp1/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF waiting _MODEL_ _MEMBER_ POST" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF waiting _MODEL_ _MEMBER_ POST2" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF waiting _MODEL_ _MEMBER_ POST3" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
+echo "SREF waiting _MODEL_ _MEMBER_ POST4" >> /gpfs/dell2/ptmp/$LOGNAME/tmpnwprd/jlogfile_sref
 
